#!/usr/bin/env bash
# this script prints `Best School` 10 times using while loop
#with some conditioal difference

y=0
while [ $y -lt 10 ]
do
  if [ $y -eq 8 ]
    then
      echo "Hi"
  else
    echo "Best School"
  fi
  y=$((y + 1))
done
