#!/usr/bin/env bash
# this script prints `Best School` 10 times using while loop
# with some conditioal difference

y=0
while [ $y -lt 10 ]
do
  if [ $y -eq 3 ]
    then
      echo "bad luck"
  elif [ $y -eq 7 ]
    then
    echo "good luck"
  else
    echo "Best School"
  fi
  y=$((y + 1))
done
