#!/usr/bin/env bash
# this script prints `Best School` 20 times using while loop
# with some conditioal difference


x=0

while [ $x -ne 13 ]
do
echo "Hour: $x"
y=1

  while [ $y -ne 60 ]
  do
    echo $y
    y=$((y + 1))
  done
  x=$((x + 1))
done
